name: Terraform Docs

on:
  push:
    branches:
      - main
    paths:
      - "modules/**/*.tf"
      - ".github/workflows/tf-docs.yml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    uses: slice-soft/ss-pipeline/.github/workflows/tf-docs.yml@v0
    with:
      module-paths: |
        modules/pages
      commit-message: "docs(terraform): update module documentation"
      pr-title: "docs(terraform): update module documentation"
      pr-body: "Automated Terraform module documentation update for ss-cloudflare-modules-iac."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
